MUSCLE (3.8) multiple sequence alignment


XP_005169417.1      ----MCARWLLLLA-----LASVACCQTVEDRAREFLNKFDEEASDIMYQYTLASWAYNT
XP_008105456.1      MASLSSSGSLLFQLYLIWNLVLLAVAQDVTQQAAEFLLQFNINAENRSYESSLASWDYNT
XP_007500942.1      ---MLDPLWLFFSL-----LAVTAAQNSIEEDAKTFLDDYNAKAEELSHQSALASWEYNT
ACT66269.1          ---MSSSSWLLLSL-----VTVTTAQSLTGENAKTFLNNFNQEAEDLSYQSSLASWNYNT
XP_044906242.1      ------------------------------------------------------------
QLF98524.1          ---MSGSSWLLLSL-----VAVTAAQSTIEEQAKTFLDKFNHEAEDLFYQSSLASWNYNT
XP_024096013.1      ---MSGSSWLLLSL-----VAVTAAQSTIEEQAKTFLDKFNHEAEDLFYQSSLASWNYNT
                                                                                

XP_005169417.1      DISQENADKEAEAYAIWSEYYNKMSEESNAYPIDQISDPIIKMQLQKLQDKGSGALSPDK
XP_008105456.1      NITEENAKRMNEVGSEWAKFYDEASQRASTFDLNNINNDTIKLQLHFLRNRGSSVLPTEK
XP_007500942.1      NITNENVEKMNEAAARWSSFYENQSSISRTYPLNEITNATVKLQLKSLQKKEGAVLSTEQ
ACT66269.1          NITEENAQKMSGAAAKWSAFYEEQSKTAQSFSLQEIQTPIIKRQLQALQQSGSSALSADK
XP_044906242.1      ------------------------------------------------------------
QLF98524.1          NITEENVQNMNNAGEKWSAFLKEQSTLAQMYPLQEIQNLTVKLQLQALQQNGSSVLSEDK
XP_024096013.1      NITEENVQNMNNAGDKWSAFLKEQSTLAQMYPLQEIQNLTVKLQLQALQQNGSSVLSEDK
                                                                                

XP_005169417.1      ASELRNIMSEMSTIYNTATVCKIDDPTDCQTLEPGLESIMAESRDYDERLHVWEGWRVAT
XP_008105456.1      YNQLNSILNKMSTIYSTGTVCKPSDPSTCLLLEPGLDIIMAESTDYSERLWAWQGWRADV
XP_007500942.1      SVRLNTILNTMSTLYSTGSVCNSETPQQCFLLEPGLDKIMDESTDYDERLWAWEGWRSKV
ACT66269.1          NKQLNTILNTMSTIYSTGKVCNPKNPQECLLLESGLDEIMATSTDYNSRLWAWEGWRAEV
XP_044906242.1      ----------MSTIYSTGKACNPNNPQECLLLEPGLDDIMENSKDYNERLWAWEGWRAEV
QLF98524.1          SKRLNTILNTMSTIYSTGKVCNPNNPQECLLLDPGLNEIMEKSLDYNERLWAWEGWRSEV
XP_024096013.1      SKRLNTILNTMSTIYSTGKVCNPNNPQECLLLEPGLNEIMANSLDYNERLWAWESWRSEV
                              ***:*.*...*: . *  *  *:.**: **  * **..**..*:.**  .

XP_005169417.1      GMKMRPLYEKYVDLKNEAAKLNNYEDHGDYWRGDYETIDDPKYSYSRDQVIEDARRIYKE
XP_008105456.1      GKKMRPLYEGYVELNNEAARSNGYADYGDYWRADYEVDFPEEYRYPRAKLITDVENTFKQ
XP_007500942.1      GKEMRPLYEEYVELKNELAKGNNYEDYGDYWRGDYEVEEPSEYVYSRPQLKKDVENTFKQ
ACT66269.1          GKQLRPLYEEYVVLKNEMARANNYNDYGDYWRGGYEAEGADGYNYNRNQLIEDVERTFAE
XP_044906242.1      GKQLRPLYEEYVALKNEMARANNYEDYGDYWRGDYEEEWTDGYNYSRSQLIKDVEHTFTQ
QLF98524.1          GKQLRPLYEEYVVLKNEMARANHYKDYGDYWRGNYEVNGVDGYDYNRDQLIEDVERTFEE
XP_024096013.1      GKQLRPLYEEYVVLKNEMARANHYEDYGDYWRGDYEVNGVDSYDYSRGQLIEDVEHTFEE
                    * ::***** ** *:** *. * * *:*****..**      * * * ::  *. . : :

XP_005169417.1      ILPLYKELHAYVRAKLQDVYPG-HIGSDACLPAHLLGDMWGRFWTNLYPLMIPYPDRPDI
XP_008105456.1      IEPLYRQLHAYVRHNLWKVYGSTNIDPNGCLPAHLLGDMWGRFWTNLYPLMIPYPAKPNI
XP_007500942.1      IKSLYEHLHAYVRRKMRNTYGS-LISETGGLPAHLLGDMWGRFWTNLYSLTMPYREKPNI
ACT66269.1          IKPLYEHLHAYVRRKLMDTYPS-YISPTGCLPAHLLGDMWGRFWTNLYPLTVPFAQKPNI
XP_044906242.1      IKPLYQHLHAYVRAKLMDTYPS-RISPTGCLPAHLLGDMWGRFWTNLYPLTVPFGQKPNI
QLF98524.1          IKPLYEHLHAYVRAKLMNAYPS-YISPTGCLPAHLLGDMWGRFWTNLYSLTVPFGQKPNI
XP_024096013.1      IKPLYEHLHAYVRAKLINAYPS-YISPIGCLPAHLLGDMWGRFWTNLYSLTVPFGQKPNI
                    * .**  ****** :: ..* .  *.  . ******************.* :*:  .*:*

XP_005169417.1      DVSSAMVEQGWDEIRLFKEAEKFFMSVNMPAMFDNFWNNSMFIKPEE-RDVVCHPTAWDM
XP_008105456.1      DVSSAMVKKNWDVTTIFKAAETFFASVGLYEMTEGFWDNSMLEEPNDGRKVVCHPTAWDL
XP_007500942.1      DVTSAMKKQNWSARRIFQEAEMFFASVGLPNMTEGFWKNSMLTEPNDGRKVVCHPTAWDL
ACT66269.1          DVTDAMMNQGWDAERIFQEAEKFFVSVGLPHMTQGFWANSMLTEPADGRKVVCHPTAWDL
XP_044906242.1      DVTDAMVNQSWDARRIFKEAEKFFVSVGLPNMTQGFWENSMLTEPGDSRKVVCHPTAWDL
QLF98524.1          DVTDAMVNQAWNAQRIFKEAEKFFVSVGLPNMTQGFWENSMLTDPGNVQKVVCHPTAWDL
XP_024096013.1      DVTDAMVDQAWDAQRIFKEAEKFFVSVGLPNMTQRFWENSMLTDPGNVQKVVCHPTAWDL
                    **:.** .: *.   :*: ** ** **.:  * : ** ***: .* : ..*********:

XP_005169417.1      GNRKDFRIKMCTKVNMDDFLTVHHEMGHNQYQMAYRNHPYLLRDGANEGFHEAVGEIMSL
XP_008105456.1      G-KNDYRIKMCTKVTMDDFLTAHHEMGHIEYDMAYSHLPLLLKGGANEGFHEAVGEIMSL
XP_007500942.1      G-KNDFRIKMCTKVTMDDFLTAHHEMGHIQYDMAYAKQPFTLRNGANEGFHEAVGEIMSL
ACT66269.1          G-HGDFRIKMCTKVTMDNFLTAHHEMGHIQYDMAYARQPFLLRNGANEGFHEAVGEIMSL
XP_044906242.1      G-KGDFRIKMCTKVTMDDFLTAHHEMGHIQYDMAYAVQPFLLRNGANEGFHEAVGEIMSL
QLF98524.1          G-KGDFRIIMCTKVTMDDFLTAHHEMGHIQYDMAYAAQPFLLRNGANEGFHEAVGEIMSL
XP_024096013.1      G-KGDFRILMCTKVTMDDFLTAHHEMGHIQYDMAYAAQPFLLRNGANEGFHEAVGEIMSL
                    * . *:** *****.**:***.****** :*:***   *  *..****************

XP_005169417.1      SAATPSHLQSLGLLPSDFKQDYETDINFLLKQALTIVGTLPFTYMLEEWRWQVFKAKIPK
XP_008105456.1      SAATPKHLKSLGLLEPTFQEDSETDINFLLKQALTIVGTMPFTYMLEKWRWMVFSGEIPN
XP_007500942.1      SAATPKHLQALGLLPPTFQEDNETEINFLFKQALTIIGTMPFTYMLENWRWMVFEGKIPK
ACT66269.1          SAATPKHLKSIGLLPSDFQEDSETEINFLLKQALTIVGTLPFIYMLEKWRWMVFRGEIPK
XP_044906242.1      SAATPNHLKTIGLLSPGFSEDSETEINFLLKQALTIVGTLPFTYMLEKWRWMVFKGEIPK
QLF98524.1          SAATPKHLKSIGLLSPDFQEDNETEINFLLKQALTIVGTLPFTYMLEKWRWMVFKGEIPK
XP_024096013.1      SAATPKHLKSIGLLSPDFQEDNETEINFLLKQALTIVGTLPFTYMLEKWRWMVFKGEIPK
                    *****.**:::*** . *.:* **:****:******:**:** ****:*** ** .:**:

XP_005169417.1      DEWMQQWWQMKRELVGVAEAVPRDETYCDPPALFHVSGDYSFIRYFTRTIYQFQFQEALC
XP_008105456.1      DQWMSKWWELKREIVGVVEPLPHDETYCDPAVLFHVANDYSFIRYYTRTIYQFQFQEALC
XP_007500942.1      EEWMKKWWEMKREIVGVVEPLPHDETYCDPAALFHVANDYSFIRYYTRTIYQFQFHKALC
ACT66269.1          EQWMKKWWEMKREIVGVVEPLRCDETYCDPASLFHVSNDYSFIRYYTRTIYQFQFQEALC
XP_044906242.1      EQWMQKWWEMKREIVGVVEPVPHDETYCDPASLFHVANDYSFIRYYTRTIYQFQFQEALC
QLF98524.1          DQWMKKWWEMKREIVGVVEPVPHDETYCDPASLFHVSNDYSFIRYYTRTLYQFQFQEALC
XP_024096013.1      DQWMKKWWEMKREIVGVVEPVPHDETYCDPASLFHVSNDYSFIRYYTRTLYQFQFQEALC
                    ::**.:**::***:***.*.:  *******. ****:.*******:***:*****::***

XP_005169417.1      KAAGHTGPLYKCDITNSTKAGDKLRHMLELGRSMSWTRALEEVAGTTKMDSQPLLHYFST
XP_008105456.1      KAAGHTEELYKCDITNSTAAGHKLRDMLALGRSQPWTKALESVTGETSMNASALLHYFEP
XP_007500942.1      KIAQPSAALHKCDITNSTEAGTKLQNMLKMGKSEPWTKALESIVGNKMMDAGPLLEYFEP
ACT66269.1          QAAKYNGSLHKCDISNSTEAGQKLLKMLSLGNSEPWTKALENVVGARNMDVKPLLNYFQP
XP_044906242.1      RIAKHEGPLHKCDISNSSEAGKKLLQMLTLGKSKPWTLALEHVVGEKKMNVTPLLKYFEP
QLF98524.1          QAAKHEGPLHKCDISNSTEAGQKLLNMLKLGKSEPWTLALENVVGAKNMNVRPLLNYFEP
XP_024096013.1      QAAKHEGPLHKCDISNSTEAGQKLLNMLRLGKSEPWTLALENVVGAKNMNVRPLLNYFEP
                    . *     *:****:**: ** **  ** :*.* .** *** :.*   *:  .** **..

XP_005169417.1      LMEWLKEENQKNNRVPGWNVNVNPEISENAFKVRISLKSALGNEAYTWNANDIYLFKSTM
XP_008105456.1      LYQWLIKNNT--GRSLEWDTAWRP-YADDEIKVRISLKAAMGNSAYTWNDNEMYLFKSTI
XP_007500942.1      LFTWLKEQNK--DAYVGWNTDWSP-YNAYKIKVRISLKT-LGENAYTWNENEMYLFQSSI
ACT66269.1          LFDWLKEQNR--NSFVGWNTEWSP-YADQSIKVRISLKSALGANAYEWTNNEMFLFRSSV
XP_044906242.1      LFTWLKEQNR--NSFVGWNTDWRP-YADQSIKVRISLKSALGDEAYEWNDNEMYLFRSSV
QLF98524.1          LFTWLKDQNK--NSFVGWSTDWSP-YADQSIKVRISLKSALGDKAYEWNDNEMYLFRSSV
XP_024096013.1      LFTWLKDQNK--NSFVGWSTDWSP-YADQSIKVRISLKSALGNKAYEWNDNEMYLFRSSV
                    *  ** .:*   .    *..   *      :*******: :* .** *. *:::**.*::

XP_005169417.1      AFAMRQYYLKEKNTDVNFTPENIHTYNETARISFKFAVMDPTKTGTVIPKAEVENAIWQE
XP_008105456.1      AYAMRQYFLIIKKETIEFRSTDIRVKNVTPRISFSFTVSMPNDSASLVPRAEVEKAISMS
XP_007500942.1      VFAMRQYFLIKKKQSIPFSNENSSC-----------------------------------
ACT66269.1          AYAMRKYFSIIKNQTVPFLEEDVRVSDLKPRVSFYFFVTSPQNVSDVIPRSEVEDAIRMS
XP_044906242.1      AYAMREYFSKVKNQTIPFVEDNVWVSNLKPRISFNFFVTASKNVSDVIPRSEVEEAIRMS
QLF98524.1          AYAMRTYFLEIKHQTILFGEEDVRVADLKPRISFNFYVTAPKNVSDIIPRTEVEEAIRIS
XP_024096013.1      AYAMRKYFLEVKNQMILFGEEDVRVANLKPRISFNFFVTAPKNVSDIIPRTEVEKAIRMS
                    .:*** *:   *:  : *   :                                      

XP_005169417.1      RDRINGAFLLSDETLEFVGLMATLAPPKEEKITIWLVVFGVVMGVTVLAGIYLVTTGILN
XP_008105456.1      RGRINEAFKLDDETLEFVGIYPTLAPPYEPPVTVWVIVFGIVVGIVVIASIALIIMGVRD
XP_007500942.1      ------------------------------PLTS--------------------------
ACT66269.1          RGRINDVFGLNDNSLEFLGIHLTLEPPYQPPVTIWLIIFGVVMALVVVGIIILIVTGIKG
XP_044906242.1      RSRINDAFRLDDNSLEFLGIQPTLSPPYQPPVTIWLIVFGVVMGVVVVGIVLLIVSGIRN
QLF98524.1          RSRINDAFRLNDNSLEFLGIQTTLAPPYQSPVTTWLIVFGVVMGVIVAGIVVLIFTGIRD
XP_024096013.1      RSRINDAFRLNDNSLEFLGIQPTLGPPNQPPVSIWLIVFGVVMGVIVVGIVVLIFTGIRD
                                                   ::                           

XP_005169417.1      R-KKKAKKAKEASVENPYDGSD--DGEVNKAFEEDIE-QTGL
XP_008105456.1      RKRRRNAAQNDLVRTDPYSN----YGENKLMSQEGINNSTTF
XP_007500942.1      ------------------------------------------
ACT66269.1          R-KKKNETKRE---ENPYDSMDIG------------------
XP_044906242.1      R-RKNNQARSE---ENPYASVDLSKGENNPGFQHADDVQTSF
QLF98524.1          R-KKKNQARSE---ENPYASIDINKGENNPGFQNTDDVQTSF
XP_024096013.1      R-KKKNKARNE---ENPYASIDISKGENNPGFQNTDDVQTSF
                                                              
